/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Bob.Ho (https://sketchfab.com/Bob.Ho)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cheese-burger-242aca8c33d64b09a339353585be366e
title: Cheese Burger
*/

import { useGLTF } from '@react-three/drei/core/useGLTF';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
type GLTFResult = GLTF & {
  nodes: any;
  materials: any;
};
export function Burger(props: any) {
  const { nodes, materials } = useGLTF(
    '/src/assets/3d-models/cheese-burger/burger.gltf'
  ) as unknown as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      scale={0.02}
      position={[9, -0.5, -5]}
      rotation={[-0.7, 1.5, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.18, 89.05, -0.27]}>
            <group position={[0, 22.97, 0]}>
              <group
                position={[46.53, -38.4, -33.42]}
                rotation={[0.73, -0.82, -0.99]}>
                <mesh
                  geometry={nodes.Sphere_2_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-25.75, -15.1, -23.76]}
                rotation={[1.29, 0.27, -0.75]}>
                <mesh
                  geometry={nodes.Sphere_3_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-27.91, -16.25, 25.55]}
                rotation={[1.85, 0.27, -2.4]}>
                <mesh
                  geometry={nodes.Sphere_4_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-24.94, -36.42, 50.45]}
                rotation={[2.63, 0.39, 1.78]}>
                <mesh
                  geometry={nodes.Sphere_5_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[5.53, -13.69, 31.21]}
                rotation={[1.95, -0.1, 2.9]}>
                <mesh
                  geometry={nodes.Sphere_8_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[12.8, -34.15, 53.62]}
                rotation={[2.65, -0.23, 1.45]}>
                <mesh
                  geometry={nodes.Sphere_9_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[7.82, -38.31, -56.78]}
                rotation={[0.48, -0.08, -1.53]}>
                <mesh
                  geometry={nodes.Sphere_10_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-11.92, -8.82, 9.43]}
                rotation={[Math.PI / 2, 0, -1.44]}>
                <mesh
                  geometry={nodes.Sphere_12_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-33.33, -39.59, -47.3]}
                rotation={[0.21, 0.6, -0.12]}>
                <mesh
                  geometry={nodes.Sphere_13_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[9.04, -32.47, 53.66]}
                rotation={[2.67, -0.08, 1.53]}>
                <mesh
                  geometry={nodes.Sphere_14_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-0.02, -13.52, 31.28]}
                rotation={[1.96, 0.03, -3.06]}>
                <mesh
                  geometry={nodes.Sphere_17_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-26.89, -22.71, 37.48]}
                rotation={[2.19, 0.38, -2.65]}>
                <mesh
                  geometry={nodes.Sphere_18_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-31.17, -15.79, 19.42]}
                rotation={[1.8, 0.32, -2.22]}>
                <mesh
                  geometry={nodes.Sphere_19_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-18.72, -39.01, 54.62]}
                rotation={[2.65, 0.23, 1.69]}>
                <mesh
                  geometry={nodes.Sphere_21_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-25.61, -35.8, 49.79]}
                rotation={[2.63, 0.39, 1.78]}>
                <mesh
                  geometry={nodes.Sphere_22_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-15.71, -18.26, 37.9]}
                rotation={[2.24, 0.28, -2.8]}>
                <mesh
                  geometry={nodes.Sphere_26_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-53.88, -32.38, -5.88]}
                rotation={[1.4, 1.09, -2.95]}>
                <mesh
                  geometry={nodes.Sphere_28_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-47.59, -27.51, -20.22]}
                rotation={[1.22, 0.63, -1.02]}>
                <mesh
                  geometry={nodes.Sphere_30_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[29.76, -16.2, 23.19]}
                rotation={[1.8, -0.32, 2.22]}>
                <mesh
                  geometry={nodes.Sphere_31_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-0.65, -21.5, -44.85]}
                rotation={[0.86, 0.06, -0.07]}>
                <mesh
                  geometry={nodes.Sphere_32_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[58.79, -44.17, -0.91]}
                rotation={[1.1, -1.38, 1.09]}>
                <mesh
                  geometry={nodes.Sphere_35_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-18.06, -23.96, 44.07]}
                rotation={[2.24, 0.28, -2.8]}>
                <mesh
                  geometry={nodes.Sphere_37_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[37.5, -21.67, 24.77]}
                rotation={[2.03, -0.57, 2.32]}>
                <mesh
                  geometry={nodes.Sphere_38_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-0.55, -8.82, -12.99]}
                rotation={[Math.PI / 2, 0, 0.65]}>
                <mesh
                  geometry={nodes.Sphere_39_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[37.02, -22.58, -27.29]}
                rotation={[1.11, -0.57, 0.82]}>
                <mesh
                  geometry={nodes.Sphere_40_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-45.76, -32.21, -28.98]}
                rotation={[0.73, 0.82, -2.15]}>
                <mesh
                  geometry={nodes.Sphere_44_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[44.53, -40.96, -37.64]}
                rotation={[0.24, -0.77, 0.17]}>
                <mesh
                  geometry={nodes.Sphere_46_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-45.03, -22.19, -7.61]}
                rotation={[1.5, 0.71, -1.46]}>
                <mesh
                  geometry={nodes.Sphere_48_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-57.3, -40.06, -9.89]}
                rotation={[1.1, 1.38, -1.09]}>
                <mesh
                  geometry={nodes.Sphere_49_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-17.96, -43.94, 55.86]}
                rotation={[2.97, 0.26, -3.1]}>
                <mesh
                  geometry={nodes.Sphere_53_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[38.81, -23.72, -27.03]}
                rotation={[1.11, -0.57, 0.82]}>
                <mesh
                  geometry={nodes.Sphere_56_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-50.76, -37.61, 25.73]}
                rotation={[2.26, 0.94, 2.35]}>
                <mesh
                  geometry={nodes.Sphere_57_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[19.45, -38.97, 54.4]}
                rotation={[2.65, -0.23, 1.45]}>
                <mesh
                  geometry={nodes.Sphere_59_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[-26.27, -26.81, -43.7]}
                rotation={[0.95, 0.38, -0.49]}>
                <mesh
                  geometry={nodes.Sphere_60_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
              <group
                position={[26.04, -12.77, 13.61]}
                rotation={[1.74, -0.35, 2.04]}>
                <mesh
                  geometry={nodes.Sphere_63_Mat7_0.geometry}
                  material={materials['Mat.7']}
                />
              </group>
            </group>
            <group position={[0, -20.39, 0]}>
              <mesh
                geometry={nodes.top_bun_1_Mat_0.geometry}
                material={materials.material}
              />
            </group>
          </group>
          <group position={[0, 55.75, 0]}>
            <group position={[0, 0.75, 0]}>
              <mesh
                geometry={nodes.Yolk_Mat12_0.geometry}
                material={materials['Mat.12']}
              />
            </group>
            <mesh
              geometry={nodes.Egg_Mat6_0.geometry}
              material={materials['Mat.6']}
            />
          </group>
          <group position={[-0.18, 49.99, -0.27]}>
            <mesh
              geometry={nodes.Lettuce_Mat10_0.geometry}
              material={materials['Mat.10']}
            />
          </group>
          <group position={[-0.18, 42.61, -0.27]}>
            <group position={[0, 6.24, -33.67]} rotation={[-0.01, -0.04, 3.14]}>
              <mesh
                geometry={nodes.Bacon_1_Mat4_0.geometry}
                material={materials['Mat.4']}
              />
              <mesh
                geometry={nodes.Bacon_1_Mat5_0.geometry}
                material={materials['Mat.5']}
              />
            </group>
            <group position={[0, 6.24, 33.4]} rotation={[0, -0.05, -Math.PI]}>
              <mesh
                geometry={nodes.Bacon_2_Mat4_0.geometry}
                material={materials['Mat.4']}
              />
              <mesh
                geometry={nodes.Bacon_2_Mat5_0.geometry}
                material={materials['Mat.5']}
              />
            </group>
            <mesh
              geometry={nodes.Bacon_Mat4_0.geometry}
              material={materials['Mat.4']}
            />
            <mesh
              geometry={nodes.Bacon_Mat5_0.geometry}
              material={materials['Mat.5']}
            />
          </group>
          <group position={[-0.18, 37.48, -0.27]}>
            <mesh
              geometry={nodes.tomato_Mat2_0.geometry}
              material={materials['Mat.2']}
            />
          </group>
          <group position={[20.56, 29.44, -32.38]}>
            <group position={[-45.66, 0, 4.58]}>
              <mesh
                geometry={nodes.cucumber_1_Mat9_0.geometry}
                material={materials['Mat.9']}
              />
              <mesh
                geometry={nodes.cucumber_1_Mat3_0.geometry}
                material={materials['Mat.3']}
              />
            </group>
            <group position={[-59.47, 0, 46.84]}>
              <mesh
                geometry={nodes.cucumber_2_Mat9_0.geometry}
                material={materials['Mat.9']}
              />
              <mesh
                geometry={nodes.cucumber_2_Mat3_0.geometry}
                material={materials['Mat.3']}
              />
            </group>
            <group position={[-22.72, 0, 70.9]}>
              <mesh
                geometry={nodes.cucumber_3_Mat9_0.geometry}
                material={materials['Mat.9']}
              />
              <mesh
                geometry={nodes.cucumber_3_Mat3_0.geometry}
                material={materials['Mat.3']}
              />
            </group>
            <group position={[14.08, 0, 44.27]}>
              <mesh
                geometry={nodes.cucumber_4_Mat9_0.geometry}
                material={materials['Mat.9']}
              />
              <mesh
                geometry={nodes.cucumber_4_Mat3_0.geometry}
                material={materials['Mat.3']}
              />
            </group>
            <mesh
              geometry={nodes.cucumber_Mat9_0.geometry}
              material={materials['Mat.9']}
            />
            <mesh
              geometry={nodes.cucumber_Mat3_0.geometry}
              material={materials['Mat.3']}
            />
          </group>
          <group
            position={[0.29, 23.3, 0.08]}
            rotation={[Math.PI, -0.71, Math.PI]}>
            <mesh
              geometry={nodes.Cheese_Mat1_0.geometry}
              material={materials['Mat.1']}
            />
          </group>
          <group position={[-0.18, 9.24, -0.27]}>
            <mesh
              geometry={nodes.beef_Mat_0.geometry}
              material={materials.Mat_0}
            />
          </group>
          <group
            position={[-0.18, -9.42, -0.27]}
            rotation={[Math.PI, -0.71, Math.PI]}>
            <mesh
              geometry={nodes.Bottom_bun_Mat_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Bottom_bun_Mat_0_1.geometry}
              material={materials.Mat_1}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/src/assets/3d-models/cheese-burger/burger.gltf');
