/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kondren53 (https://sketchfab.com/Kondren53)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/a83570f93a02440aa3a80fdf0ed90c4b
title: кубик рубик
*/
import { useGLTF } from '@react-three/drei/core/useGLTF';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
type GLTFResult = GLTF & {
  nodes: any;
  materials: any;
};
export function Rubics(props: any) {
  const { nodes, materials } = useGLTF(
    'src/assets/3d-models/rubics-cube/rubics.gltf'
  ) as unknown as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      position={[5, 0, -3]}
      scale={6}
      rotation={[-0.1, 1, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-0.05, 0.03, 0.73]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.13}>
          <mesh
            geometry={nodes['������_0'].geometry}
            material={materials['.001']}
          />
        </group>
        <group
          position={[-0.06, 0.03, 0.73]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.06}>
          <mesh
            geometry={nodes['������001_0'].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.05, 0.15, 0.62]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.88}>
          <mesh
            geometry={nodes['������002_0'].geometry}
            material={materials['.004']}
          />
        </group>
        <group
          position={[0.05, -0.08, 0.6]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={0.88}>
          <mesh
            geometry={nodes['������003_0'].geometry}
            material={materials['.005']}
          />
        </group>
        <group
          position={[-0.18, -0.08, 0.62]}
          rotation={[0, 0, -Math.PI]}
          scale={0.88}>
          <mesh
            geometry={nodes['������004_0'].geometry}
            material={materials['.006']}
          />
        </group>
        <group
          position={[0.05, -0.1, 0.84]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.88}>
          <mesh
            geometry={nodes['������005_0'].geometry}
            material={materials['.007']}
          />
        </group>
        <group
          position={[0.05, 0.14, 0.85]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.88}>
          <mesh
            geometry={nodes['������006_0'].geometry}
            material={materials['.008']}
          />
        </group>
        <group
          position={[0.06, -0.08, 0.84]}
          rotation={[-Math.PI, 0, 0]}
          scale={0.88}>
          <mesh
            geometry={nodes['������007_0'].geometry}
            material={materials['.009']}
          />
        </group>
        <group position={[-0.06, 0.15, 0.73]} scale={0.04}>
          <mesh
            geometry={nodes['������010_0'].geometry}
            material={materials['.002']}
          />
        </group>
        <group
          position={[-0.06, 0.03, 0.6]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.04}>
          <mesh
            geometry={nodes['������008_0'].geometry}
            material={materials['.019']}
          />
        </group>
        <group
          position={[-0.06, -0.1, 0.73]}
          rotation={[Math.PI, -Math.PI / 2, 0]}
          scale={0.04}>
          <mesh
            geometry={nodes['������009_0'].geometry}
            material={materials['.007']}
          />
        </group>
        <group
          position={[-0.06, 0.03, 0.85]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.04}>
          <mesh
            geometry={nodes['������011_0'].geometry}
            material={materials['.018']}
          />
        </group>
        <group
          position={[-0.18, 0.03, 0.73]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.04}>
          <mesh
            geometry={nodes['������012_0'].geometry}
            material={materials['.012']}
          />
        </group>
        <group
          position={[0.07, 0.03, 0.73]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.04}>
          <mesh
            geometry={nodes['������013_0'].geometry}
            material={materials['.013']}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('src/assets/3d-models/rubics-cube/rubics.gltf');
